// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VdBreadcrumb: typeof import('./src/components/vd-breadcrumb.vue')['default']
    VdCard: typeof import('./src/components/vd-card.vue')['default']
    VdCardChart: typeof import('./src/components/vd-card-chart.vue')['default']
    VdChart: typeof import('./src/components/vd-chart.vue')['default']
    VdField: typeof import('./src/components/vd-field.vue')['default']
    VdFormButton: typeof import('./src/components/vd-form-button.vue')['default']
    VdIconBox: typeof import('./src/components/vd-icon-box.vue')['default']
    VdListBar: typeof import('./src/components/vd-list-bar.vue')['default']
    VdPagination: typeof import('./src/components/vd-pagination.vue')['default']
    VdSearch: typeof import('./src/components/vd-search.vue')['default']
    VdSimpleTable: typeof import('./src/components/vd-simple-table.vue')['default']
    VdStatistic: typeof import('./src/components/vd-statistic.vue')['default']
    VdSvgIcon: typeof import('./src/components/vd-svg-icon.vue')['default']
    VdTag: typeof import('./src/components/vd-tag.vue')['default']
    VdToast: typeof import('./src/components/vd-toast.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
